stages:
  - build
  - lint
  - test

build-backend:
  stage: build
  image: rust:latest
  needs: []
  script:
    - cd backend
    - cargo build

format-backend:
  stage: lint
  image: rust:latest
  needs: []
  script:
    - cd backend
    - cargo fmt --check

lint-backend:
  stage: lint
  image: rust:latest
  needs: []
  script:
    - cd backend
    - cargo clippy -- -Dwarnings

test-backend:
  stage: test
  image: rust:latest
  needs: []
  script:
    - cd backend
    - cargo test

build-frontend:
  stage: build
  image: node:latest
  script:
    - cd frontend
    - npm install
    - npm run build

format-frontend:
  stage: lint
  image: node:latest
  needs: []
  script:
    - cd frontend
    - npm install
    - npm run format:check

lint-frontend:
  stage: lint
  image: node:latest
  needs: []
  script:
    - cd frontend
    - npm install
    - npm run lint:check
