[package]
name = "backend"
version = "0.0.0"
edition = "2024"

[profile.release]
opt-level = 2
lto = "thin"

[dependencies]
axum = { version = "0.8.4", default-features = false, features = ["http1", "json", "original-uri", "tokio"] }
bytes = { version = "1.10.1", default-features = false }
chrono = { version = "0.4.41", default-features = false, features = ["clock"] }
clap = { version = "4.5.38", features = ["derive"] }
colored = { version = "3.0.0", default-features = false }
convert_case = { version = "0.8.0", default-features = false }
dashmap = { version = "6.1.0", default-features = false }
flume = { version = "0.11.1" }
log = { version = "0.4.27", default-features = false, features = ["std"] }
regex = { version = "1.11.1" }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.140", default-features = false }
serde_repr = { version = "0.1.20", default-features = false }
strum = { version = "0.27.1", default-features = false, features = ["derive"] }
thiserror = { version = "2.0.12", default-features = false }
tokio = { version = "1.45.0", default-features = false, features = ["macros", "net", "rt-multi-thread", "signal"] }
tower-http = { version = "0.6.4", default-features = false, features = ["fs", "trace"] }
tracing = { version = "0.1.41", default-features = false }
tracing-subscriber = { version = "0.3.19", default-features = false, features = ["ansi", "fmt"] }
validator = { version = "0.20.0", default-features = false, features = ["derive"] }
webrtc = { version = "0.13.0" }

[target.'cfg(unix)'.dependencies]
filedescriptor = { version = "0.8.3", default-features = false }
systemd-journal-logger = { version = "2.2.2", default-features = false }
